### ISSUE TITLE
Does not work when Full Screen Mode activated

### ISSUE THREAD

**Issue by jweinstein-lms** [zeroclipboard/zeroclipboard#263]
There is a jquery plugin which allows you to display a portion of the page in Full Screen mode. However, when I put the browser in Full Screen Mode, ZeroClipboard no longer functions. 

Using the Chrome's "Inspect Element" I was able to determine that the embedded SWF flash objects were still on the page, but showing up **behind** the HTML elements they were supposed to cover. Tried changing CSS z-index without any luck. Moved the Flash object from the document.body to the DIV that is being displayed in full screen but that only worked for one of the two buttons `glued` by ZeroClipbard. Also need to move back to the document.body and re-intialize when they leave full screen mode.

Any advice for getting this ZeroClipboard to work in Full Screen Mode?

Tested on Chrome 30 and Firefox 24 on Win 7 with Flash 11.9.900

**Comment by JamesMGreene** [comment]
I'm going to close this for now as there is no way to resolve the conflict with the HTML TopLayer specification without altering our embedding strategy [which, as discussed, as other potential negative implications but can be achieved independently by interested parties by extending ZeroClipboard.Core].

I've created and applied a new label of "HTML TopLayer" so that this issue can be easily found and revisited once browsers start implementing the HTML Clipboard API (see #171).
