### ISSUE TITLE
Synthetic events can't be prevented from bubbling

### ISSUE THREAD

**Issue by meleyal** [zeroclipboard/zeroclipboard#434]
It seems the synthetic events fired on the clipped element can't be prevented from bubbling.
http://jsfiddle.net/meleyal/7GgFC/13/

My use case is the button should copy the url if ZC is enabled (and prevent the link opening), otherwise it should open the url.

**Comment by bfrohs** [comment]
The method used in https://github.com/zeroclipboard/zeroclipboard/issues/434#issuecomment-45249194 breaks keyboard accessibility (eg, pressing `Enter` on button/link doesn't do anything). An alternative approach would be to emit the `_click` event from JavaScript from an `aftercopy` listener. That way, a `bubbleClick` property could be added to the `aftercopy` event that, if set to false, would prevent the `_click` event from being emitted.

It could also be emitted from ZeroClipboard.as, but I'm not sure how reliable that is for getting returned data (or if it's even possible).

**Comment by JamesMGreene** [comment]
@bfrohs: I'm not positive I understand your scenario.  Can you explain a bit further?  It would be super helpful to have:
 - [ ] A step-by-step description of the user actions that lead into your scenario.
 - [ ] An explanation of the expected behavior
 - [ ] An explanation of the current/actual behavior
 - [ ] Code that shows the behavior you are expecting working correctly (with/without ZeroClipboard involved would be fine)
 - [ ] Code that shows the behavior you are expecting **NOT** working correctly (_with_ ZeroClipboard involved)
