### ISSUE TITLE
ZeroClipboard doesn't work concatenated with other libraries using Grunt

### ISSUE THREAD

**Issue by cmgustavo** [zeroclipboard/zeroclipboard#484]
I use Grunt to minify all libraries. Just ZeroClipboard doesn't work, and I have to put it separated.

**Comment by nanopony** [comment]
@JamesMGreene
not sure that it will help much during the investigation, but from time to time I was experiencing the following issue with zeroclipboard bundled with other libs and minified via yuglify:

    * v2.2.0
    */
    ,function(){var e,t,n,r,i,s,o,u,a,f,l,c,h,p,d,v,m,g,y,b,w,E,S,x,T,N,C,k,L,A,O,M,_,D,P,H,B,j,F,I,q,R,U,z,W,X,V,$,J,K=[].slice
Basically, it puts excessive comma at the start of the line just after the license section. I think that it is uglify issue, because it appears on very random basis. I'll add the info if I dig into some understanding

**Comment by JamesMGreene** [comment]
@nanopony: Hmm, strange, thanks for the info. As far as I had seen, most minifiers prefer putting a `;` at the start, if anything, so seeing the `,` operator there is indeed interesting.

**Comment by nanopony** [comment]
@JamesMGreene
Yes, it is very odd behavior indeed and it was causing the syntax error because the previous line before the comments was ending with comma as well; 
Also I still can't put my finger on but my further experiments proved that zeroclipboard was the victim, not the cause - if I remove it from the bundle the same effect was appearing on one another library which was succeeding it in the bundle. Ultimately, the oddness disappeared after I removed medium,js (which also was having one more side effect: license jsdocs from its source code was misplaced in final minified bundle, preceding totally random libs -- so it is very likely to be uglifiy issue). So, I must apologize for my false speculation - though I think if anyone will came here via google with the similar issues like I did, they will fix it faster :)

**Comment by JamesMGreene** [comment]
Aw, fantastic info. Thanks, @nanopony!

**Comment by jsymons-vc** [comment]
@JamesMGreene I was having this issue today whilst testing in a folder on my desktop. It was chiming in with the "flash-deactivated" error in FF and Chrome so I know it was loading, the swf was loading fine too with the correct type too. Then I took the files and ran them through xampp and now it works fine. Maybe it doesn't like relative paths or needs absolute paths to work properly?

I set the project up with browserify, if that helps?
