### ISSUE TITLE
zeroclipboard can't overlay HTML5 <dialog> with only z-index

### ISSUE THREAD

**Issue by ThiRaBrTNK** [zeroclipboard/zeroclipboard#542]
To overlay HTML5 ```<dialog>``` properly, ```<div>``` should be placed within ```<dialog>```.

**Comment by JamesMGreene** [comment]
Really!? Blah... which browser(s)?

The browser vendor(s)' implementation of `dialog` must basically be leveraging the same concept as the Fullscreen API (see Issue #263), which isolates all outside DOM from the display even if it would normally be present above (on top of) it `z-index`-wise.

See #536 for available workarounds (some requiring other ZeroClipboard fixes first) that you can use for now, including customizing the DOM placement procedure yourself by using "ZeroClipboard.Core.js" instead of "ZeroClipboard.js".

**Comment by ThiRaBrTNK** [comment]
I thought I could patch this easily, searching for appropriate container for embedding, but since you have reasons to have only one swf embedded for multiple clients… I can't think of a good enough solution.

**Comment by ThiRaBrTNK** [comment]
Btw, you were right about similarity to the Fullscreen API, HTML5 ```dialog``` refers to the concept called 'top layer' from the Fullscreen API. http://www.w3.org/html/wg/drafts/html/master/interactive-elements.html#the-dialog-element http://www.w3.org/html/wg/drafts/html/master/infrastructure.html#top-layer

**Comment by JamesMGreene** [comment]
I'm going to close this for now as there is no way to resolve the conflict with the HTML TopLayer specification without altering our embedding strategy (which, as discussed, as other potential negative implications but can be achieved independently by interested parties by extending ZeroClipboard.Core.

I've created and applied a new label of "HTML TopLayer" so that this issue can be easily found and revisited once browsers start implementing the HTML Clipboard API (see #171).
