### ISSUE TITLE
v1.3.5 IE10 problems with positioning

### ISSUE THREAD

**Issue by EduardTrayan** [zeroclipboard/zeroclipboard#556]
Hello.

I have a floating problem in IE10: sometimes active button, which we use for copy features, becomes unclicable and there is no hover action. It's a rare problem, but it exists. 
I found some differences in positioning between good and bad cases
* good case: `left: 0px; top: -9999px; width: 43px; height: 43px; position: absolute; z-index: 999999999;` - position of `.global-zeroclipboard-container` without hover
* bad case: `left: 848.53px; top: 499.7px; width: 43px; height: 43px; position: absolute; z-index: 999999999;` without hover

Could you please assist with this problem?

Thank you in advance

**Comment by JamesMGreene** [comment]
Please upgrade to the `v2.x` series and retest your scenario. I am not willing to investigate or fix `v1.x` issues anymore and `v2.x` is chock-full of bug fixes and enhancements. Be aware its API is almost completely changed (mostly just method and event renaming but the event callback signature changed as well).

If you need to support IE < 9, you can use `v2.0.2`; otherwise you can use the latest version (currently `v2.2.0`).

**Comment by EduardTrayan** [comment]
Thanks, I'll try asap
