### ISSUE TITLE
Copying HTML to clipboard on Windows 8.1/IE11

### ISSUE THREAD

**Issue by angrygoats** [zeroclipboard/zeroclipboard#573]
Hey everyone.

I am trying to copy an html table to Excel. In testing I noticed that using ZeroClipboard via any method will not copy html to a clipboard in IE11 on Windows 8.1. It seems to work fine in Chrome 41. I have tried every method on [this page](https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#text-to-copy). The issue seems to be originating from the fact IE (and it seems like Safari as well) does not support copying 'text/html' to the clipboard natively. Unfortunately, I really need text/html support.

Does anyone have a work around for this, or can offer me some advice on how to fix this? It's a very strange issue.

**Comment by JamesMGreene** [comment]
What's your ZeroClipboard version?

Offhand, your description makes it sound like your copy isn't even going through ZeroClipboard. Is the "ready" event triggering? Are any "error" events triggering?

Can you please provide a simple JSBin/JSFiddle/CodePen example that reproduces your problem? We have some starter snippets that you can fork: [docs/instructions.md#starter-snippets-for-playground-sites](https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#starter-snippets-for-playground-sites)

Also, when you mention Safari not working: which version and which OS?

**Comment by angrygoats** [comment]
@JamesMGreene 

Hey, thanks for your reply. It looks like I am running ZeroClipboard 2.2.0. There are no error messages that are triggered, and it's definitely able to console.log from the ready event.

Even though for some reason the table html isn't being copied totally correctly (this)[http://fiddle.jshell.net/k9psq1da/69/show] JSfiddle demonstrates the problem. I've tested this fiddle in Windows 8.1/IE11 and it fails. 

I have tried OS X/Yosemite and it seems to be working now. I will talk to the person who caught the OS X bug and see if I can get any more information.

**Comment by JamesMGreene** [comment]
The problem is your code. :blush: 

Check out the updated JSFiddle: http://fiddle.jshell.net/k9psq1da/74/

I've fixed 3 problems, only 1 of which was the real issue:
 - You were setting a config option called `moviePath`, which does not exist. That was renamed to `swfPath` in v2.0.0
 - You were trying to set plain text with the MIME type `"text/text"` rather than `"text/plain"`
 - **REAL PROBLEM:** the data you were putting into the clipboard was the `table` element's _**innerHTML**_ (via jQuery's `$(el).html()`), so it was missing the wrapping `<table></table>` markup. Obviously that plays an important role in HTML portability for a pasting target.
     - I switched it to use `el.outerHTML` instead. If you want to go the jQuery-heavy route, by all means, use my jQuery `outerHtml` plugin: [JamesMGreene/jquery.outerHtml](https://github.com/JamesMGreene/jquery.outerHtml). :wink:

With those changes, it worked just fine for me in IE11 and pasting into Word and Excel.

**Comment by angrygoats** [comment]
@JamesMGreene I'll give this a shot and see how it goes. Thanks for your help!

**Comment by JamesMGreene** [comment]
That sounds like a problem with the paste target/receiver (Google Sheets), yes.

Have you had any success manually copying an HTML table (just by selecting it and doing a browser/OS copy to the clipboard) and then pasting it into Google Sheets?
