### ISSUE TITLE
Security.allowInsecureDomain("*"); pleaaaaaase

### ISSUE THREAD

**Issue by kud** [zeroclipboard/zeroclipboard#584]
Could you add `Security.allowInsecureDomain("*");` in your flash?

http://stackoverflow.com/questions/18298049/externalinterface-call-works-but-javascript-cant-access-actionscript-callbacks

We have some troubles with http/https and you need this line in the flash to make it work.

**Comment by kud** [comment]
Okay I've read this:

- https://github.com/zeroclipboard/zeroclipboard/blob/f0263698a4123376bb46bbd814fd968f48b9def1/docs/instructions.md#cross-protocol-limitations
- https://github.com/zeroclipboard/zeroclipboard/issues/170#issuecomment-19116143

Why did you choose this strategy, not to allow insecure domain?

Is it possible to use flashvars to enable or disable this?

Thank you.

**Comment by JamesMGreene** [comment]
Absolutely not. :-1: :smile:

Adding that would potentially enable any source on the page (the page itself, unsandboxed `iframe`s, third party ads, etc.) to use your ZeroClipboard SWF as a Flash XSS attack vector.

Serving pages of mixed content (both `http://` and `https://` resources coexisting simultaneously) is also a security vulnerability that enables man-in-the-middle attacks on the HTTP resources that can gain access to the otherwise safely encrypted HTTPS resources. Some browsers will outright block such mixed content resources.

https://developer.mozilla.org/en-US/docs/Security/MixedContent

**Comment by kud** [comment]
Okay thank you. Makes sense. :)
