### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jrvidal** [zeroclipboard/zeroclipboard#641]
Plunker: https://plnkr.co/edit/Em69LeFyaukJx9qowOlW
Chrome version: 49.0.2623.87 (64-bit)

The plunker code is very simple: on every click, it either creates and stores a new ZeroClipboard instance or destroys the current one.

To reproduce the leak:
- Open plunker.
- Click the "Clip" button a couple of times.
- Take a heap snapshot in Chrome.
- Click the button again, furiously.
- Take another snapshot.
- Compare snapshots 1 vs. 2. In particular, look for instances of the `ZeroClipboard` constructor.

From poking around in the "Retainers" view, I think the problem is the [wildcard event](https://github.com/zeroclipboard/zeroclipboard/blob/d88febee4d1f9e6d6a347978dae4c545fd48985f/dist/ZeroClipboard.js#L2095):

``` javascript
ZeroClipboard.on("*", function(event) {
  return client.emit(event);
});
```

It looks like `off` does not clean this callback when an instance is destroyed.

**Comment by JamesMGreene** [comment]
Wow, thanks for the detailed investigation!

**Comment by arunsinghdeveloper** [comment]
Hi Team,
I am using 1.0.7 version of Zeroclipboard and it's leaking lot of memory while expending the multiple data on page. It's consuming approximately 40 to 50 MB per click and also found the problem is inside clip.glue("") statement.

 var clip = new ZeroClipboard.Client();
 clip.setHandCursor(true);
 clip.glue(copyButtons[x]); <=========

**Comment by JamesMGreene** [comment]
@arunsinghdeveloper: We haven't supported the ZeroClipboard `v1.x` series of releases for a very long time. Please upgrade to a newer version.
