### ISSUE TITLE
test failure on new dom node

### ISSUE THREAD

**Issue by SidKwok** [zeroclipboard/zeroclipboard#649]
when I try to `glue ` my new button, it can't help.
```
$('.index-buttons').append('<a id="copy-token">test</a>');
var clip = new ZeroClipboard.Client();
...
clip.glue("copy-token");
```

is there a better way to fix it?

**Comment by JamesMGreene** [comment]
Your code is all using the ZeroClipboard `v1.x` API.  If that is your intent, be sure to actually use that version of the library for both JS and SWF: https://github.com/zeroclipboard/zeroclipboard/tree/1.x-master

Otherwise, please correct all of your code to use the `v2.x` API.  If you are transitioning from `v1.x` to `v2.x`, the following documentation will likely help you:  [1.x-master@docs/instructions.md#deprecations](https://github.com/zeroclipboard/zeroclipboard/blob/1.x-master/docs/instructions.md#deprecations)
