### ISSUE TITLE
client.on is not a function(…)

### ISSUE THREAD

**Issue by nancy-grow** [zeroclipboard/zeroclipboard#669]
on()  is not a function

**Comment by JamesMGreene** [comment]
This bug is unfortunately completely impossible to investigate unless you provide us with some manner of useful information.

 - [ ] How are you including ZeroClipboard (e.g. from a local folder, from a CDN, etc.)?
 - [ ] What browser are you using?
 - [ ] Please paste the contents of the following command after inputting it into a developer console:
     `console.log( JSON.stringify( ZeroClipboard.state() ) );`

**Comment by JamesMGreene** [comment]
Also, can you show us at least a small snippet of your code?

**Comment by nancy-grow** [comment]
i used it by seajs require
ZeroClipboard  is a objet
thank you for your answer. I have solved it.
